### PR TITLE
Add Camel-addon to addons set

### PR DESCRIPTION
**Pull request by oscerd**
Hi,

This PR contains the data related to Apache Camel forge addon from Fabric8 Team.

Thank you.

### CODE REVIEW

**Comment by gastaldi** [comment]
Thank you

**Comment by davsclaus** [comment]
Yay thanks @oscerd nice to see it on the website.

**Comment by oscerd** [comment]
It's a pleasure :-)

**Comment by gastaldi** [comment]
Hi @oscerd and @davsclaus.

I noticed that http://forge.jboss.org/addon/io.fabric8.forge:camel documentation is empty. Would it be possible to point to an Asciidoc file containing the instructions in http://fabric8.io/guide/forge.html ?

Thanks!

**Comment by oscerd** [comment]
Hi, George.

I think it's possible.

I'll open a ticket on Fabric8 project :-)

**Comment by oscerd** [comment]
Hi George.

Now we have a specific Asciidoc related to Camel Forge addon.

https://github.com/fabric8io/fabric8/blob/master/forge/addons/camel/README.asciidoc

**Comment by gastaldi** [comment]
Thanks! Now it looks like there is an issue with our renderer. We're
working on it

On Thu, Aug 27, 2015 at 1:12 PM, Andrea Cosentino <notifications@github.com>
wrote:

> Hi George.
>
> Now we have a specific Asciidoc related to Camel Forge addon.
>
>
> https://github.com/fabric8io/fabric8/blob/master/forge/addons/camel/README.asciidoc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forge/website-data/pull/14#issuecomment-135481611>.
>



-- 
*George Gastaldi | Senior Software Engineer*

JBoss Forge Team
T: +55 11 3524-6169
M: +55 47 9711-1000

**Comment by oscerd** [comment]
Let me know if I can do something. One thing I was thinking of is the
following: is there a problem if we specify fabric8 git repository in our
camel add-on metadata, while the asciidoc file is placed in a sub-module of
fabric8 project?

I ask this because I was looking at the others add-on and they all have a
dedicated repo with the asciidoc file in root..
Il 27/ago/2015 19:30, "George Gastaldi" <notifications@github.com> ha
scritto:

**Comment by gastaldi** [comment]
Usually people use addon-install-from-git to install the addons, that's why
a separate repo is better.
We're facing a "Disk Quota exceeded" error in our Asciidoc renderer
(Redoculous).
Em 27/08/2015 18:21, "Andrea Cosentino" <notifications@github.com> escreveu:

**Pull request merged**
